# This template is pre-configured to create an applyable run in Terraform Cloud.
# If the plan phase is successful, the run will be applied for the specified workspace.
#
# This workflow is configured to trigger when a push against your `main` branch occurs,
# **IF** the set paths contain files that have changed.
#
---
name: Terraform Cloud Apply Run

on:
  push:
    branches:
    ## RECOMMENDED: Change for your target branch, or include branches you wish to trigger this workflow file.
      - main
    paths:
      - "deploy-vpc/*.tfvars"

## RECOMMENDED: Limit apply runs job / workflow to a single concurrency group at a time.
## link: https://docs.github.com/en/actions/using-jobs/using-concurrency
## Example:
# concurrency: production

jobs:
  terraform-apply-vpc:
    uses: ./.github/workflows/terraform-apply-template.yml
    with:
      tf_workspace: ${{ vars.TF_WORKSPACE_VPC }}
      tf_directory:  "components/vpc"
      tf_vars_directory: "deploy-vpc"
      tf_api_token: ${{ secrets.TF_API_TOKEN }}
