on:
  workflow_call:
    inputs:
      tf_workspace:
        description: 'The Terraform Cloud workspace to run the apply in'
        required: true
        type: string
      tf_vars_directory:
        description: 'The directory containing the Terraform var file'
        required: true
        type: string
      tf_directory:
        description: 'The directory containing the Terraform configuration'
        required: true
        type: string
      tf_var_aws_allowed_account_id:
        description: 'The account ids terraform is allowed to operate on'
        required: true
        type: string
      tf_region:
        description: 'aws region'
        required: true
        type: string
  

jobs:
  terraform-cloud-apply:
    runs-on: ubuntu-latest
    env:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORG }}
      TF_VAR_aws_allowed_account_id : ${{ inputs.tf_var_aws_allowed_account_id }}
      TF_REGION: ${{ inputs.tf_region }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy terraform.tfvars to target directory
        run: |
          cp ./${{ inputs.tf_vars_directory }}/terraform.tfvars ./${{ inputs.tf_directory }}
          envsubst '$TF_REGION' < ./components/vpc/providers.tf > ./components/vpc/providers-tmp.tf
          mv ./${{ inputs.tf_directory }}/providers-tmp.tf ./${{ inputs.tf_directory }}/providers.tf

      - name: Upload configuration to Terraform Cloud
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.1.1
        id: upload
        with:
          workspace: ${{ inputs.tf_workspace }}-${{ inputs.tf_region }}
          directory: ${{ inputs.tf_directory }}

      - name: Create Terraform Cloud run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.1.1
        id: create-run
        with:
          workspace: ${{ inputs.tf_workspace }}-${{ inputs.tf_region }}
          configuration_version: ${{ steps.upload.outputs.configuration_version_id }}

      - name: Apply Terraform Cloud run
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.1.1
        id: apply
        if: ${{ fromJSON(steps.create-run.outputs.payload).data.attributes.actions.is_confirmable }}
        with:
          run: ${{ steps.create-run.outputs.run_id }}
          comment: "Apply Run from GitHub Actions CI ${{ github.sha }}"