on:
  pull_request:
    branches:
      - main
    paths:
      - "deploy-vpc/**"
  push:
    branches:
      - main
    paths:
      - "deploy-vpc/**"


jobs:
  vpc:
    uses: ./.github/workflows/main.yml
    with:
      tf_vars_directory: "deploy-vpc"
      tf_directory: "components/vpc"
      tf_workspace_prefix: "aws-terraform-demo-vpc"